 # https://github.com/webiny/action-conventional-commits

# TEST 1
# feat: update action conventional commits
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3232
# success

# TEST 2
# fixup! feat: update action conventional commits
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3232
# fails: According to the conventional-commits specification, some of the commit messages are not valid.

# TEST 3
# docs: update action conventional commits
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3232
# success

# TEST 4
# feat!: send an email to the customer when a product is shipped
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3231
# success

# TEST 5
# feat(api)!: send an email to the customer when a product is shipped
# Introduce a request id and a reference to latest request. Dismiss
# incoming responses other than from latest request.
# 
# Remove timeouts which were used to mitigate the racing issue but are
# obsolete now.
# 
# Reviewed-by: Z
# Refs: #123
# success

name: Action Conventional Commits

on:
  push:
   branches:
      - main

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, for private repositories.
          allowed-commit-types: "feat,fix,docs,style,refactor,perf,test,chore" # Optional, set if you want a subset of commit types to be allowed.