name: Pull Request Workflow

on:
  pull_request:
    branches:
      - '*'  # Trigger on all branches for pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Maven
        uses: s4u/maven-settings-action@v3.0.0

      - name: Clean
        run: ./build.sh clean
        working-directory: ./build

      - name: Test
        run: ./build.sh commitStage
        working-directory: ./build
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'build/target/testReports/*.xml' 
