 # https://github.com/marketplace/actions/generate-changelog-action

name: 'Generate Changelog Action'
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      id: Changelog