 # https://github.com/marketplace/actions/gs-commit-message-checker?version=v2.0.0

# TEST 1
# feat: update action conventional commits
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3232
# success

# TEST 2
# fixup! feat: update action conventional commits
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3232
# success

# TEST 3
# docs: update action conventional commits
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3232
# success

# TEST 4
# feat!: send an email to the customer when a product is shipped
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3231
# fails

# TEST 5
# feat(api)!: send an email to the customer when a product is shipped
# Introduce a request id and a reference to latest request. Dismiss
# incoming responses other than from latest request.
# 
# Remove timeouts which were used to mitigate the racing issue but are
# obsolete now.
# 
# Reviewed-by: Z
# Refs: #123
# fails

name: 'GS Commit Message Checker'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(fixup! )?(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .{1,100}$'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "(fixup! )?(feat|fix|docs|style|refactor|perf|test|chore): text".'
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^ING-[0-9]+$'
          error: 'You need at least one "ING-<issue number>" line.'