 # https://github.com/marketplace/actions/gs-commit-message-checker?version=v2.0.0

# TEST 1
# feat: update action conventional commits
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3232
# fails

# TEST 2
# fixup! feat: update action conventional commits
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3232
# success

# TEST 3
# docs: update action conventional commits
# BREAKING CHANGE: `extends` key in config file is now used for extending other config files
# ING-3232
# success

name: 'GS Commit Message Checker'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(fixup! )?(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .{1,100}$'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^#].{200}'
          error: 'The maximum line length of 200 characters is exceeded.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^ING-[0-9]+$'
          error: 'You need at least one "ING-<issue number>" line.'