 # https://github.com/marketplace/actions/gs-commit-message-checker?version=v2.0.0
name: 'GS Commit Message Checker'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  check-commit-message:
    name: GS Commit Message Checker
    runs-on: ubuntu-latest
    steps:
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^.+(ING)\-[0-9]+$'
          error: 'You need at least one "ING-<issue number>" line.'
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^.+(feat|fix|docs|style|refactor|perf|test|chore): .+$'
          error: 'Your first line has to contain a commit type like "feat: your_title".'    